
apiVersion: v1
kind: Secret
metadata:
  name: argocd-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:panchanandevops/argocd-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCDms7znmzV2vjES92rKKuaYEYSKooHy3lnT8WpKCYdPwAAAKC9og8RvaIP
    EQAAAAtzc2gtZWQyNTUxOQAAACCDms7znmzV2vjES92rKKuaYEYSKooHy3lnT8WpKCYdPw
    AAAECgvnSo1wHp78qBKQbbETKOWlLs6JTFCarIdFvVLljkr4OazvOebNXa+MRL3asoq5pg
    RhIqigfLeWdPxakoJh0/AAAAGXBhbmNoYW5hbmRldm9wc0BnbWFpbC5jb20BAgME
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
